# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mModel', models.CharField(max_length=50)),
                ('mType', models.CharField(max_length=50)),
                ('mSerial', models.CharField(max_length=50)),
                ('mYear', models.DateField()),
                ('mWeight', models.IntegerField()),
                ('mSpeed', models.IntegerField()),
                ('mCapacity', models.IntegerField()),
                ('mWeightCapacity', models.IntegerField()),
                ('mFuelCapacity', models.IntegerField()),
                ('mFuelConsumption', models.IntegerField()),
                ('mLong', models.FloatField()),
                ('mLat', models.FloatField()),
                ('mIsAvailable', models.BooleanField()),
                ('mFuelLevel', models.FloatField()),
            ],
        ),
    ]
