# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='mIsAvailable',
            new_name='isAvailable',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='mModel',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='mSerial',
            new_name='serial',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='mType',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='mCapacity',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='mFuelCapacity',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='mFuelConsumption',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='mFuelLevel',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='mLat',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='mLong',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='mSpeed',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='mWeight',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='mWeightCapacity',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='mYear',
        ),
        migrations.AddField(
            model_name='machine',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='fuelCapacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='fuelConsumption',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='fuelLevel',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='lng',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='modalYear',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='speed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='weightCapacity',
            field=models.IntegerField(null=True),
        ),
    ]
