# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='Name',
            new_name='name',
        ),
    ]
