# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Love',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lover', models.CharField(max_length=50)),
                ('ageOfLove', models.IntegerField()),
            ],
        ),
    ]
